-- this file is generated by program!
-- never modify it!!!
-- source file: building.csv

local building = {}

building.house = {
    use_money = 1000,
    use_food = 123,
    is_init = true,
    defense = 100,
}

why!!!!!!!!!!!!!!!!!

