-- this file is generated by program!
-- never modify it!!!
-- source file: building.csv

local building = {}

building.house = {
    use_money = 1000,
    use_food = 123,
    is_init = true,
    defense = 100,
}

building.house[1] = {
    use_money = 1000,
    use_food = 123,
    is_init = true,
    defense = 100,
}

building.house[2] = {
    use_money = 123,
    defense = 120,
}

building.house[3] = {
    use_money = 456,
    defense = 130,
}

building.farm = {
    use_money = 100,
    use_food = 234,
    is_init = false,
    defense = 200,
}

building.farm[1] = {
    use_money = 100,
    use_food = 234,
    is_init = false,
    defense = 200,
}

building.farm[2] = {
    use_money = 200,
}

building.farm[3] = {
    use_money = 200,
}

building.farm[4] = {
}

